name: "CI"

on:
  push:
    paths:
      - ".github/**/*"
      - "*.ts"
      - "**/*.ts"
      - "deno.json"
      - "deno.lock"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - run: deno run ci
