name: "Release"
on: workflow_dispatch
permissions:
  contents: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm i -D --no-save conventional-changelog-conventionalcommits @semantic-release/git @sebbo2002/semantic-release-jsr
      - name: "Release"
        uses: cycjimmy/semantic-release-action@v4
        with:
          semantic_version: 24.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
